<a href="https://colab.research.google.com/github/navyashree1105/Python_Basics/blob/main/Python%20functions%20and%20oops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
1).To create sequences of numbers, NumPy provides a function __________ analogous
to range that returns arrays instead of lists.
a) arange
b) aspace
c) aline
d) all of the mentioned

a)arange

In [ ]:
2) Point out the correct statement.
a) NumPy main object is the homogeneous multidimensional array
b) In Numpy, dimensions are called axes
c) Numpy array class is called ndarray
d) All of the mentioned

d) all of the mentioned

In [ ]:
3) Which of the following array shapes is NOT compatible for broadcasting with an
array of shape (3, 1, 4)?
a) (3, 5, 1)
b) (1, 4)
c) (3, 4)
d) (4,)

all are compatible

In [ ]:
4) What does np.linspace(0, 10, 5) return?
a) [0, 2, 4, 6, 8]
b) [0., 2.5, 5., 7.5, 10.]
c) [0, 10, 5]
d) [0., 2., 4., 6., 8., 10.]

b)[0.,2.5,5.,7.5,10.]

In [ ]:
5) Which attribute tells you the number of dimensions of a NumPy array?
a) shape
b) size
c) ndim
d) rank

c)ndim

In [ ]:
6) What happens if you try to reshape an array into an incompatible shape?
a) Returns None
b) Pads with zeros
c) Raises ValueError
d) Automatically adjusts shape

c)Raises ValueError

In [ ]:
7) What is the result of np.full((2,2), 7)?
a) [[0, 0], [0, 0]]
b) [[7, 7], [7, 7]]
c) [[1, 1], [1, 1]]
d) Error

b)[[7,7],[7,7]]

In [ ]:
8) What is the result of np.arange(1, 10, 3)?
                                 start,end,step=3
a) [1, 4, 7]
b) [1, 3, 6, 9]
c) [1, 2, 3]
d) [1, 10, 3]

a)[1,4,7]

In [ ]:
9) What does np.random.rand() return?
a) Random integer
b) Random float between 0 and 1
c) Random float between -1 and 1
d) Always 0

b)Random float between 0 and 1

In [ ]:
10) What does np.random.randint(1, 5) return?
a) Float between 1 and 5
b) Integer between 1 and 4
c) Integer between 1 and 5
d) Always 1

c)Integer between 1 and 4

In [ ]:
#11. Given an array, replace all even numbers with 0.
import numpy as np
a=np.arange(0,10)
a[a%2==0]=0
print(a)

[0 1 0 3 0 5 0 7 0 9]


In [ ]:
#12. Create two arrays and perform element-wise addition, subtraction, and multiplication.

a=np.array([1,2,3])
b=np.array([7,11,9])
print("Addition=",a+b)
print("Subtraction=",a-b)
print("Multiplication=",a*b)


Addition= [ 8 13 12]
Subtraction= [-6 -9 -6]
Multiplication= [ 7 22 27]


In [ ]:
#13. Create a checkerboard pattern (0 and 1) of size 10 x 10.
a=np.zeros(100)
b=a.reshape(10,10)
#print(b)
#print(b.ndim)
b[0,1::2]=1
b[0::2,1::2]=1
b[1,0::2]=1
b[1::2,0::2]=1
print(b)

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
arr=np.zeros(100)
brr=arr.reshape(10,10)
#print(brr)
brr[0,::2]=1
brr[::2,::2]=1
brr[1::2,1]=1
#brr[]
print(brr)

[[1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#14.  Count how many times a specific value appears in an array.
arr=np.array([11,45,87,45,98,67,45,90,87,99,88,45,9])
count = np.count_nonzero(arr == 45)
print(count)

4


In [ ]:
#15. Generate 20 random integers between 1 and 50 and find their average. Set a seed and
#generate the same random array twice. Shuffle the array randomly.
a=np.random.seed(0)
a=np.random.randint(1,51,20)
print(a)
print("average=",np.average(a))
np.random.shuffle(a)
print("shuffled array=",a)

[45 48  1  4  4 40 10 20 22 37 24  7 25 25 13  2 39 40 24 47]
average= 23.85
shuffled array= [10 13 39 24 20 48  2  7  1 25 24 47 45  4  4 37 22 25 40 40]


In [ ]:
#16. Create a random array and print only values greater than its mean.

a=np.random.randint(1,10,5)
print(a)
print("mean=",np.mean(a))
a[a>np.mean(a)]

[2 3 2 5 7]
mean= 3.8


array([5, 7])

In [ ]:
#17. Simulate rolling a dice 100 times using NumPy. Create the frequency table of every
#output.
rolls = np.random.randint(1, 7, 100)
freq = np.bincount(rolls)[1:]
print(freq)

[22 12 15 19 19 13]


In [ ]:
#18. Write a function to check if a number is a palindrome without converting to string.
def is_palindrome(n):
    if n < 0:
        return False

    digits = []
    while n > 0:
        digits.append(n % 10)
        n //= 10

    arr = np.array(digits)
    return np.array_equal(arr, arr[::-1])
print(is_palindrome(121))
print(is_palindrome(123))

True
False


In [ ]:
#19. Write a program to find the longest word in a sentence.(Words are seperated by space).
def longest_word(sentence):
    return max(sentence.split(), key=len)

In [ ]:
longest_word("I am learning the concepts of python")

'learning'

Given a string, compress it like:

1.
Input: "aaabbc"
Output: "a3b2c1"


2.
Input: "abcd"
Output: "a1b1c1d1"


3.
Input: "aabbaa"
Output: "a2b2a2"


4.
Input: "aaaaa"
Output: "a5"


5.
Input: "" (empty string)
Output: ""


6.
Input: "aAaA"
Output: "a1A1a1A1"


7.
Input: "aaAAaa"
Output: "a2A2a2"

In [ ]:
def compress_string(s):
    res, count = "", 1
    for i in range(1, len(s)+1):
        if i < len(s) and s[i] == s[i-1]:
            count += 1
        else:
            if i > 0:
                res += s[i-1] + str(count)
            count = 1
    return res

In [ ]:
compress_string("aaabbc")

'a3b2c1'

In [ ]:
compress_string("abcd")

'a1b1c1d1'

In [ ]:
compress_string("aabbaa" )

'a2b2a2'

In [ ]:
compress_string("aaaaa")

'a5'

In [ ]:
compress_string("")

''

In [ ]:
compress_string("aAaA")

'a1A1a1A1'

In [ ]:
compress_string("aaAAaa")

'a2A2a2'